const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('./models/Product');

dotenv.config();

const sampleProducts = [
  {
    name: 'Premium Cotton T-Shirt',
    barcode: 'TSH001',
    price: 599,
    stock: 50,
    category: 'T-Shirts',
    minStock: 20,
    size: 'M',
    color: 'Navy Blue',
    brand: 'FashionHub',
    gender: 'Men',
    description: 'Comfortable cotton t-shirt with modern fit',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 25
  },
  {
    name: 'Slim Fit Denim Jeans',
    barcode: 'JNS001',
    price: 1899,
    stock: 30,
    category: 'Jeans',
    minStock: 15,
    size: '32',
    color: 'Dark Blue',
    brand: 'DenimCo',
    gender: 'Men',
    description: 'Classic slim fit denim jeans',
    discountEnabled: true,
    discountPercent: 5,
    maxDiscountForSales: 10,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Floral Summer Dress',
    barcode: 'DRS001',
    price: 2499,
    stock: 25,
    category: 'Dresses',
    minStock: 10,
    size: 'L',
    color: 'Floral Print',
    brand: 'StyleWear',
    gender: 'Women',
    description: 'Beautiful floral print summer dress',
    discountEnabled: true,
    discountPercent: 15,
    maxDiscountForSales: 20,
    maxDiscountForAdmin: 30
  },
  {
    name: 'Casual Hoodie',
    barcode: 'HOD001',
    price: 1499,
    stock: 40,
    category: 'Hoodies',
    minStock: 10,
    size: 'XL',
    color: 'Grey',
    brand: 'Comfort+',
    gender: 'Unisex',
    description: 'Warm and comfortable hoodie',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 25
  },
  {
    name: 'Formal Shirt',
    barcode: 'SHT001',
    price: 1299,
    stock: 35,
    category: 'Shirts',
    minStock: 15,
    size: 'L',
    color: 'White',
    brand: 'FormalWear',
    gender: 'Men',
    description: 'Classic formal shirt for office wear',
    discountEnabled: true,
    discountPercent: 5,
    maxDiscountForSales: 10,
    maxDiscountForAdmin: 15
  },
  {
    name: 'Kids Cotton Shorts',
    barcode: 'SHR001',
    price: 399,
    stock: 60,
    category: 'Shorts',
    minStock: 20,
    size: '8-10Y',
    color: 'Multi',
    brand: 'KidsFun',
    gender: 'Kids',
    description: 'Comfortable cotton shorts for kids',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Sports Track Pants',
    barcode: 'TRK001',
    price: 999,
    stock: 45,
    category: 'Track Pants',
    minStock: 15,
    size: 'M',
    color: 'Black',
    brand: 'ActiveWear',
    gender: 'Unisex',
    description: 'Perfect for workouts and casual wear',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Designer Kurta',
    barcode: 'KRT001',
    price: 1799,
    stock: 20,
    category: 'Ethnic Wear',
    minStock: 10,
    size: 'M',
    color: 'Maroon',
    brand: 'EthnicStyle',
    gender: 'Women',
    description: 'Traditional designer kurta',
    discountEnabled: true,
    discountPercent: 15,
    maxDiscountForSales: 20,
    maxDiscountForAdmin: 25
  },
  {
    name: 'Leather Jacket',
    barcode: 'JKT001',
    price: 4999,
    stock: 15,
    category: 'Jackets',
    minStock: 5,
    size: 'L',
    color: 'Black',
    brand: 'Leather Co',
    gender: 'Men',
    description: 'Premium leather jacket',
    discountEnabled: true,
    discountPercent: 5,
    maxDiscountForSales: 10,
    maxDiscountForAdmin: 15
  },
  {
    name: 'Yoga Pants',
    barcode: 'YGA001',
    price: 899,
    stock: 55,
    category: 'Activewear',
    minStock: 20,
    size: 'M',
    color: 'Purple',
    brand: 'YogaFit',
    gender: 'Women',
    description: 'Stretchable yoga pants',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Polo T-Shirt',
    barcode: 'PLO001',
    price: 799,
    stock: 40,
    category: 'T-Shirts',
    minStock: 15,
    size: 'L',
    color: 'Red',
    brand: 'PoloClub',
    gender: 'Men',
    description: 'Classic polo t-shirt',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Maxi Dress',
    barcode: 'MXD001',
    price: 2199,
    stock: 18,
    category: 'Dresses',
    minStock: 8,
    size: 'M',
    color: 'Blue',
    brand: 'StyleWear',
    gender: 'Women',
    description: 'Elegant maxi dress',
    discountEnabled: true,
    discountPercent: 15,
    maxDiscountForSales: 20,
    maxDiscountForAdmin: 25
  },
  {
    name: 'Cargo Pants',
    barcode: 'CRG001',
    price: 1399,
    stock: 32,
    category: 'Pants',
    minStock: 12,
    size: '32',
    color: 'Khaki',
    brand: 'Adventure',
    gender: 'Men',
    description: 'Durable cargo pants',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Blazer',
    barcode: 'BLZ001',
    price: 3499,
    stock: 12,
    category: 'Blazers',
    minStock: 5,
    size: 'L',
    color: 'Navy',
    brand: 'FormalWear',
    gender: 'Men',
    description: 'Professional blazer',
    discountEnabled: true,
    discountPercent: 5,
    maxDiscountForSales: 10,
    maxDiscountForAdmin: 15
  },
  {
    name: 'Kids T-Shirt Pack',
    barcode: 'KTP001',
    price: 699,
    stock: 50,
    category: 'T-Shirts',
    minStock: 20,
    size: '6-8Y',
    color: 'Assorted',
    brand: 'KidsFun',
    gender: 'Kids',
    description: 'Pack of 3 colorful t-shirts',
    discountEnabled: true,
    discountPercent: 15,
    maxDiscountForSales: 20,
    maxDiscountForAdmin: 25
  },
  {
    name: 'Winter Jacket',
    barcode: 'WJK001',
    price: 2999,
    stock: 22,
    category: 'Jackets',
    minStock: 10,
    size: 'XL',
    color: 'Brown',
    brand: 'WinterWear',
    gender: 'Unisex',
    description: 'Warm winter jacket',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Palazzo Pants',
    barcode: 'PLZ001',
    price: 999,
    stock: 38,
    category: 'Pants',
    minStock: 15,
    size: 'Free Size',
    color: 'Beige',
    brand: 'EthnicStyle',
    gender: 'Women',
    description: 'Comfortable palazzo pants',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Graphic T-Shirt',
    barcode: 'GTS001',
    price: 599,
    stock: 65,
    category: 'T-Shirts',
    minStock: 25,
    size: 'M',
    color: 'Black',
    brand: 'StreetStyle',
    gender: 'Unisex',
    description: 'Trendy graphic print t-shirt',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Denim Jacket',
    barcode: 'DJK001',
    price: 2499,
    stock: 18,
    category: 'Jackets',
    minStock: 8,
    size: 'L',
    color: 'Light Blue',
    brand: 'DenimCo',
    gender: 'Unisex',
    description: 'Classic denim jacket',
    discountEnabled: true,
    discountPercent: 10,
    maxDiscountForSales: 15,
    maxDiscountForAdmin: 20
  },
  {
    name: 'Saree with Blouse',
    barcode: 'SRE001',
    price: 3999,
    stock: 10,
    category: 'Ethnic Wear',
    minStock: 5,
    size: 'Free Size',
    color: 'Red & Gold',
    brand: 'TraditionalWear',
    gender: 'Women',
    description: 'Elegant saree with matching blouse',
    discountEnabled: true,
    discountPercent: 15,
    maxDiscountForSales: 20,
    maxDiscountForAdmin: 30
  }
];

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Delete existing products
    await Product.deleteMany({});
    console.log('Existing products cleared');

    // Insert sample products
    await Product.insertMany(sampleProducts);
    console.log(`${sampleProducts.length} products added to inventory`);

    console.log('\n✅ Sample products seeded successfully!\n');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding products:', error);
    process.exit(1);
  }
};

seedProducts();
